### ISSUE TITLE
Training: TypeError: __init__() takes from 1 to 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by TreyWi** [ThomasLamsonFr/AITextGenerator#8]
Any suggestions? I was just trying to train using your code on the original file but keep getting errors cropping up I've been blocked by this one. 

AITextGenerator/src/json_generation/paragraph_preprocessing.py", line 20, in separate_paragraphs_all_files
    parser = ParagraphParser(min_threshold, min_length, max_length)
TypeError: __init__() takes from 1 to 2 positional arguments but 4 were given

**Comment by ThomasLamsonFr** [comment]
Hello, I pushed a commit to master branch that should fix the issue. Didn't test it though but it's simple enough.
Simply put, we changed our ParagraphParser at some point to handle paragraph sizes by itself, randomizing them along the way ; and we forgot to change it in the initialization of the parser in the function you pointed out.

**Comment by ThomasLamsonFr** [comment]
I'll let the issue open until you confirm it solved the problem! :)

**Comment by TreyWi** [comment]
It fixed the problem and successfully got past the point it had an error above. I see how you fixed it... I was way off down left field and appreciate the assistance. I'm just replicating what you did prior to trying my own datasets so you may see me asking more questions. Great work. Appreciate it.
