### ISSUE TITLE
Error between screen and seat

### ISSUE THREAD

**Issue by TreyWi** [ThomasLamsonFr/AITextGenerator#9]
I've gotten the full data.py to run and I believe you instruct the next step to be finetuning.py but when I try and run that I don't know what parameters to input. Do I need to install gpt-2 separately? Can you provide the command you run to train? 

python3 finetuning.py --train_data_file /data/summaries/preproc_BART --output_dir /models/generation --model_type bert --mlm .1

I do not see what will generate the "data_output/metrics_raw.csv" either, does finetuning?
Thanks

**Comment by TreyWi** [comment]
I think I figured it out

!python3 finetuning.py \
    --output_dir='/content/drive/My Drive/AITextGenerator/data_output' \
    --model_type=gpt2 \
    --model_name_or_path=gpt2-medium \
    --save_total_limit=5 \
    --num_train_epochs=1.0 \
    --do_train \
    --evaluate_during_training \
    --logging_steps=500 \
    --save_steps=500 \
    --train_data_file='/content/drive/My Drive/AITextGenerator/data/summaries/Preproc_BART/' \
    --per_gpu_train_batch_size=2 \
    --per_gpu_eval_batch_size=2 \
    --block_size=64 \
    --gradient_accumulation_steps=5 \
    --overwrite_output_dir

**Comment by ThomasLamsonFr** [comment]
Hello, just saw your issue, sorry.

Indeed, that's a good set of arguments.
I would recommend trying out several parameters for gpu batch sizes, trying to get as high as possible. However, the size of GPT-2 requires the model to run on a very good GPU if you want something as 8 or 16 as a batch size.
